config/routes.rb
Rails.application.routes.draw do

  get 'statistics/', to: 'statistics#index'
  get 'students/', to: 'students#index'
  root 'project#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 55 }
  validates :email, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="d-flex justify-content-end">
  <%= link_to 'Anicamp Pro', root_path,  class: 'navbar-brand '%>
  </div>
  <div clss="d-flex justify-content">
  <a class="navbar-brand" href="#">Tips</a>
  <a class="navbar-brand" href="#">Global Lessons</a>
  <%= link_to 'Students', students_path, class: 'navbar-brand' %>
  </div>
  <div class="d-flex justify-content-end">
  <a class="navbar-brand float-right" href="#">Invite Student</a>
  <a class="navbar-brand float-right" href="#">Profile</a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anicamp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <%= render 'layouts/navbar' %>
  
  <%= yield %>
  
  </body>
</html>

app/views/project/index.html.erb
<div class="container mt-5">
<div class="alert alert-primary" role="alert">
  Current notice to all your students!
</div>
  <div class="row">
    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Teacher Statistics</h4>
          <h6 class="card-subtitle mb-2 text-muted">Common information</h6>
          <p class="card-text">
          <small>
          <p>Total Students: 9</p>
          <p>Total Video Uploads: 32</p>
          
          </small>
          <%= link_to 'View All Statistics', statistics_path, class: 'card-link' %>
        </div>
      </div>
    </div>
    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Recent Video Uploads</h4>
          <h6 class="card-subtitle mb-2 text-muted">Links</h6>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="card-link">View All Uploads</a>
        </div>
      </div>
    </div>
    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Recent Comments</h4>
          <h6 class="card-subtitle mb-2 text-muted">Links</h6>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="card-link">View All Comments</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-sm">
      <%= render '/comments.html' %>
    </div>
  </div>
</div>

app/views/statistics/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam cursus leo in lorem interdum convallis. Cras mauris erat, tincidunt non nisl sed, aliquam vestibulum ligula. Proin a arcu quis elit volutpat sodales. In nec interdum nisl. In feugiat ultricies tincidunt. Fusce vitae augue sit amet nisi porta commodo. Nam aliquet nibh a urna efficitur varius. Curabitur aliquam neque in velit dictum laoreet. Pellentesque sed dolor feugiat, lacinia nisl at, iaculis magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et cursus nisl. Aliquam euismod odio et gravida ultrices.</p>

      <p>Fusce fringilla, ipsum at hendrerit pellentesque, lorem ipsum tempor neque, nec ullamcorper nisl erat maximus odio. Morbi sit amet condimentum arcu. Fusce cursus pellentesque porttitor. Integer vitae elit sed eros lobortis facilisis eu euismod dolor. Nunc ut ipsum sit amet eros consequat consectetur vel quis risus. Phasellus scelerisque iaculis dolor, condimentum ultrices erat eleifend at. Curabitur non placerat nisl. Quisque ut vulputate arcu, in dignissim felis.</p>

      <p>Nullam orci velit, venenatis at urna vel, ullamcorper luctus massa. Suspendisse potenti. Suspendisse potenti. Sed congue eu lacus at scelerisque. Maecenas eget ultricies purus, ac vestibulum lorem. Nulla facilisi. Aenean ut mauris sit amet purus auctor rhoncus. Donec iaculis justo sit amet laoreet viverra. Nam tempus nunc ut felis gravida, vel maximus dolor interdum. Morbi nibh lorem, lacinia a tempor sit amet, venenatis a ligula. Sed in quam facilisis, efficitur orci eget, lacinia leo.JUNK</p>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Username</th>
          <th scope="col">Last Lesson</th>
          <th scope="col">Video Library</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Mark</td>
          <td>Otto</td>
          <td>@mdo</td>
          <td>Date</td>
          <td>Link</td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Jacob</td>
          <td>Thornton</td>
          <td>@fat</td>
          <td>Date</td>
          <td>Link</td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Larry</td>
          <td>the Bird</td>
          <td>@twitter</td>
          <td>Date</td>
          <td>Link</td>
        </tr>
      </tbody>
    </table>
  </div>
  </div>
</div>